#include <functional>
#include <gsl/gsl_sf.h>
#include <dlfcn.h>
#include <string>
#include <vector>

std::vector<std::string> GSLFunArray = {
    "gsl_sf_airy_Ai", 
    "gsl_sf_airy_Bi", 
    "gsl_sf_airy_Ai_scaled",
    "gsl_sf_airy_Bi_scaled",
    "gsl_sf_airy_Ai_deriv", 
    "gsl_sf_airy_Bi_deriv", 
    "gsl_sf_airy_Ai_deriv_scaled",
    "gsl_sf_airy_Bi_deriv_scaled",
    "gsl_sf_bessel_J0",
    "gsl_sf_bessel_J1",
    "gsl_sf_bessel_Y0",
    "gsl_sf_bessel_Y1",
    "gsl_sf_bessel_I0",
    "gsl_sf_bessel_I1",
    "gsl_sf_bessel_I0_scaled",
    "gsl_sf_bessel_I1_scaled",
    "gsl_sf_bessel_K0",
    "gsl_sf_bessel_K1",
    "gsl_sf_bessel_K0_scaled",
    "gsl_sf_bessel_K1_scaled",
    "gsl_sf_bessel_j0",
    "gsl_sf_bessel_j1",
    "gsl_sf_bessel_j2",
    "gsl_sf_bessel_y0",
    "gsl_sf_bessel_y1",
    "gsl_sf_bessel_y2",
    "gsl_sf_bessel_i0_scaled",
    "gsl_sf_bessel_i1_scaled",
    "gsl_sf_bessel_i2_scaled",
    "gsl_sf_bessel_k0_scaled",
    "gsl_sf_bessel_k1_scaled",
    "gsl_sf_bessel_k2_scaled",
    "gsl_sf_clausen",
    "gsl_sf_dawson",
    "gsl_sf_debye_1",
    "gsl_sf_debye_2",
    "gsl_sf_debye_3",
    "gsl_sf_debye_4",
    "gsl_sf_debye_5",
    "gsl_sf_debye_6",
    "gsl_sf_dilog",
    "gsl_sf_ellint_Kcomp", 
    "gsl_sf_ellint_Ecomp", 
    "gsl_sf_ellint_Dcomp", 
    "gsl_sf_erfc",
    "gsl_sf_log_erfc",
    "gsl_sf_erf",
    "gsl_sf_erf_Z",
    "gsl_sf_erf_Q",
    "gsl_sf_hazard",
    "gsl_sf_exp",
    "gsl_sf_expm1",
    "gsl_sf_exprel",
    "gsl_sf_exprel_2",
    "gsl_sf_expint_E1",
    "gsl_sf_expint_E2",
    "gsl_sf_expint_E1_scaled",
    "gsl_sf_expint_E2_scaled",
    "gsl_sf_expint_Ei",
    "gsl_sf_expint_Ei_scaled",
    "gsl_sf_Shi",
    "gsl_sf_Chi",
    "gsl_sf_expint_3",
    "gsl_sf_Si",
    "gsl_sf_Ci",
    "gsl_sf_atanint",
    "gsl_sf_fermi_dirac_m1",
    "gsl_sf_fermi_dirac_0",
    "gsl_sf_fermi_dirac_1",
    "gsl_sf_fermi_dirac_2",
    "gsl_sf_fermi_dirac_mhalf",
    "gsl_sf_fermi_dirac_half",
    "gsl_sf_fermi_dirac_3half",
    "gsl_sf_lngamma",
    "gsl_sf_gamma",
    "gsl_sf_gammastar",
    "gsl_sf_gammainv",
    "gsl_sf_lambert_W0",
    "gsl_sf_lambert_Wm1",
    "gsl_sf_legendre_P1",
    "gsl_sf_legendre_P2",
    "gsl_sf_legendre_P3",
    "gsl_sf_legendre_Q0",
    "gsl_sf_legendre_Q1",
    "gsl_sf_log",
    "gsl_sf_log_abs",
    "gsl_sf_log_1plusx",
    "gsl_sf_log_1plusx_mx",
    "gsl_sf_psi",
    "gsl_sf_psi_1piy",
    "gsl_sf_psi_1",
    "gsl_sf_sin_pi",
    "gsl_sf_cos_pi",
    "gsl_sf_synchrotron_1",
    "gsl_sf_synchrotron_2",
    "gsl_sf_transport_2",
    "gsl_sf_transport_3",
    "gsl_sf_transport_4",
    "gsl_sf_transport_5",
    "gsl_sf_sin",
    "gsl_sf_cos",
    "gsl_sf_sinc",
    "gsl_sf_lnsinh",
    "gsl_sf_lncosh",
    "gsl_sf_zeta",
    "gsl_sf_zetam1",
    "gsl_sf_eta"
};
const std::vector<std::function<double(double)>> GSLFuncList = {
    // gsl_sf_airy.h
    std::bind(gsl_sf_airy_Ai, std::placeholders::_1, GSL_PREC_DOUBLE),
    std::bind(gsl_sf_airy_Bi, std::placeholders::_1, GSL_PREC_DOUBLE),
    std::bind(gsl_sf_airy_Ai_scaled, std::placeholders::_1, GSL_PREC_DOUBLE),
    std::bind(gsl_sf_airy_Bi_scaled, std::placeholders::_1, GSL_PREC_DOUBLE),
    std::bind(gsl_sf_airy_Ai_deriv, std::placeholders::_1, GSL_PREC_DOUBLE),
    std::bind(gsl_sf_airy_Bi_deriv, std::placeholders::_1, GSL_PREC_DOUBLE),
    std::bind(gsl_sf_airy_Ai_deriv_scaled, std::placeholders::_1, GSL_PREC_DOUBLE),
    std::bind(gsl_sf_airy_Bi_deriv_scaled, std::placeholders::_1, GSL_PREC_DOUBLE),
    // gsl_sf_bessel.h
    gsl_sf_bessel_J0,
    gsl_sf_bessel_J1,
    gsl_sf_bessel_Y0,
    gsl_sf_bessel_Y1,
    gsl_sf_bessel_I0,
    gsl_sf_bessel_I1,
    gsl_sf_bessel_I0_scaled,
    gsl_sf_bessel_I1_scaled,
    gsl_sf_bessel_K0,
    gsl_sf_bessel_K1,
    gsl_sf_bessel_K0_scaled,
    gsl_sf_bessel_K1_scaled,
    gsl_sf_bessel_j0,
    gsl_sf_bessel_j1,
    gsl_sf_bessel_j2,
    gsl_sf_bessel_y0,
    gsl_sf_bessel_y1,
    gsl_sf_bessel_y2,
    gsl_sf_bessel_i0_scaled,
    gsl_sf_bessel_i1_scaled,
    gsl_sf_bessel_i2_scaled,
    gsl_sf_bessel_k0_scaled,
    gsl_sf_bessel_k1_scaled,
    gsl_sf_bessel_k2_scaled,
    // gsl_sf_clausen.h
    gsl_sf_clausen,
    // gsl_sf_coulomb.h
    // gsl_sf_coupling.h
    // gsl_sf_dawson.h
    gsl_sf_dawson,
    // gsl_sf_debye.h
    gsl_sf_debye_1,
    gsl_sf_debye_2,
    gsl_sf_debye_3,
    gsl_sf_debye_4,
    gsl_sf_debye_5,
    gsl_sf_debye_6,
    // gsl_sf_dilog.h
    gsl_sf_dilog,
    // gsl_sf_elementary.h
    // gsl_sf_ellint.h
    std::bind(gsl_sf_ellint_Kcomp, std::placeholders::_1, GSL_PREC_DOUBLE),
    std::bind(gsl_sf_ellint_Ecomp, std::placeholders::_1, GSL_PREC_DOUBLE),
    std::bind(gsl_sf_ellint_Dcomp, std::placeholders::_1, GSL_PREC_DOUBLE),
    // gsl_sf_elljac.h
    // gsl_sf_erf.h
    gsl_sf_erfc,
    gsl_sf_log_erfc,
    gsl_sf_erf,
    gsl_sf_erf_Z,
    gsl_sf_erf_Q,
    gsl_sf_hazard,
    // gsl_sf_exp.h
    gsl_sf_exp,
    gsl_sf_expm1,
    gsl_sf_exprel,
    gsl_sf_exprel_2,
    // gsl_sf_expint.h
    gsl_sf_expint_E1,
    gsl_sf_expint_E2,
    gsl_sf_expint_E1_scaled,
    gsl_sf_expint_E2_scaled,
    gsl_sf_expint_Ei,
    gsl_sf_expint_Ei_scaled,
    gsl_sf_Shi,
    gsl_sf_Chi,
    gsl_sf_expint_3,
    gsl_sf_Si,
    gsl_sf_Ci,
    gsl_sf_atanint,
    // gsl_sf_fermi_dirac.h
    gsl_sf_fermi_dirac_m1,
    gsl_sf_fermi_dirac_0,
    gsl_sf_fermi_dirac_1,
    gsl_sf_fermi_dirac_2,
    gsl_sf_fermi_dirac_mhalf,
    gsl_sf_fermi_dirac_half,
    gsl_sf_fermi_dirac_3half,
    // gsl_sf_gamma.h
    gsl_sf_lngamma,
    gsl_sf_gamma,
    gsl_sf_gammastar,
    gsl_sf_gammainv,
    // gsl_sf_gegenbauer.h
    // gsl_sf_hermite.h
    // gsl_sf_hyperg.h
    // gsl_sf_laguerre.h
    // gsl_sf_lambert.h
    gsl_sf_lambert_W0,
    gsl_sf_lambert_Wm1,
    // gsl_sf_legendre.h
    gsl_sf_legendre_P1,
    gsl_sf_legendre_P2,
    gsl_sf_legendre_P3,
    gsl_sf_legendre_Q0,
    gsl_sf_legendre_Q1,
    // gsl_sf_log.h
    gsl_sf_log,
    gsl_sf_log_abs,
    gsl_sf_log_1plusx,
    gsl_sf_log_1plusx_mx,
    // gsl_sf_mathieu.h
    // gsl_sf_pow_int.h
    // gsl_sf_psi.h
    gsl_sf_psi,
    gsl_sf_psi_1piy,
    gsl_sf_psi_1,
    // gsl_sf_sincos_pi.h
    gsl_sf_sin_pi,
    gsl_sf_cos_pi,
    // gsl_sf_synchrotron.h
    gsl_sf_synchrotron_1,
    gsl_sf_synchrotron_2,
    // gsl_sf_transport.h
    gsl_sf_transport_2,
    gsl_sf_transport_3,
    gsl_sf_transport_4,
    gsl_sf_transport_5,
    // gsl_sf_trig.h
    gsl_sf_sin,
    gsl_sf_cos,
    gsl_sf_sinc,
    gsl_sf_lnsinh,
    gsl_sf_lncosh,
    // gsl_sf_zeta.h
    gsl_sf_zeta,
    gsl_sf_zetam1,
    gsl_sf_eta
};
